# Generated by Django 3.1.2 on 2020-11-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='reports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
